### ISSUE TITLE
Non-linear by default, linearity by graded modality.

### ISSUE THREAD

**Issue by dorchard** [dorchard/granule#15]
This is more of a research question than an issue. What if the basis of Gram was not a linear type theory, but just a usual Cartesian theory? The graded modalities would still provide a facility in which we are saying "track how information flows from/to this variable/value" but if we want to write our usual functional programs we could, and then gradually morph them into graded versions?

"Normal linearity" can then be recovered by the `Nat=` coeffect type. For example:
```
id : a |1 : Nat=| -> a
id |x| = x
```
Essentially, we could add linearity as a modality, defining a type synonym like:
```
type Linear a = a |1 : Nat=|
```
There might be some soundness proofs to check... but this seems quite natural to me.

**Comment by heades** [comment]
I am pondering this now.  One question, currently, with the linear base, do we have a way of saying, the variable, `x`, can be used *any number of times*, or do we always have to essentially pick a number?

**Comment by dorchard** [comment]
In theory we do, but in the implementation it doesn't work yet. The `Nat*` coeffect type has the element`*` which is the top-completion of natural numbers, so you can use this to say "any number". It doesn't work yet, because I need to slightly restructure the way SMT constraints are generated in order to provide this.

**Comment by heades** [comment]
Thanks, I am putting together a list of pros and cons about this.  So far your proposal is winning.  More soon.

**Comment by heades** [comment]
I am starting to think this is more than an alternate path, and much more the right path.  Below I argue that making this change has a number of positive effects across the board.

Functional Programming
-------------------------

@dorchard  has already highlighted the benefit from a functional programming perspective.  It would allow for functional programming as usual.  Anyone coming from, say, Haskell would feel right at home, but with a number of new and interesting features.

This is great, but there are more benefits than this.

Extending the Language
------------------------

We want to move towards dependent types, and right now, with a linear base, this is a complex problem.  Moving to fully linear dependent types is an open problem, and while we can inclemently move to a combination of linear logic and non-linear dependent types it is difficult to incrementally expand the language from there.

Now move to a non-linear base -- cartesian closed -- we know exactly how to expand the base language to dependent types.  The interesting part is how the graded effects/coeffects interact with dependency, but this can be introduced incrementally in a more natural way than with a linear base.  We can run experiments far more quickly.

Semantics
---------

The language design with a non-linear base is cleaner.  It is straightforward to work at both extremes.  Linearity is simple to enforce, and working with unlimited resources is simple too, unlike the current design.  We need something special in order to handle the unlimited case as noted by @dorchard.

I also think the categorical model will be cleaner, because we know how the model of the base will be, and working out how the modalities factor in will be super interesting.  I actually find the linearity as an effect to be extremely interesting.

So I think this is a good idea.

**Comment by dorchard** [comment]
Thank you for this analysis. I agree with your points. I think "Linearity as a Coeffect" could be a paper in itself. The only splinter in my mind still is about conjunction/disjunction (products/sums) and their multiplicative/additive flavours. At the moment, we don't have these anyway, but we probably should, and we might need to make sure they transfer over into the linearity coeffect story.

If we take additive disjunction to be 
`A ⊕ B = A |1=| + B |1=|` 
and multiplicative conjunction (⊗) to be 
`A ⊗ B = A |1=| x B |1=|`
is this is the same as additive conjunction &?
What about multiplicative disjunction? 

I'm a little unsure.

**Comment by dorchard** [comment]
Actually, I think I have been a bit foolish: I don't think this can work as initially stated. What about the following function:
```
dub : Int |1=| -> Int
dub x = let |a : Int| = x in let |b : Int| = x in a + b
```
Currently this won't type check in Gram as `x` is used twice-- but if we turned off linear types it would type check because we have cloned `x` *whilst it is still boxed*. 

The only solution I can see is to make unboxing implicit so that you can never pass round a boxed value and duplicate it. This has one advantage: manual unboxing is a syntactic pain. However, I worry about what effect it this has on the power of the system (at least from the point of view as a core calculus).

**Comment by dorchard** [comment]
So after discussing with @heades, I am now fairly convinced that this can only work if coeffects are applied to every variable automatically (and tracked automatically). One way to do this is to  follow the original two coeffect papers, where everything lives directly in the coKleisli category for the graded comonad. I don't think we can provide this feature in Granule as-is, without redesigning the language. If there were some higher-level language that did this, then Granule would make an excellent typed core language in which to compile to... this could be an interesting project. But I think for now this isn't quite the aim of Granule. So...do we close this project issue or should we keep it so the idea doesn't float out of our heads?

**Comment by vimuel** [comment]
There's probably no harm in leaving it open with an appropriate tag.

**Comment by heades** [comment]
Yeah, I propose to keep it, but label it “research question” to indicate that it is an interesting
question.

**Comment by vimuel** [comment]
I agree, @heades, I can't create tags, so the best I found was "project" + "wontfix", but I agree "research question" or "research idea" would be better, @dorchard.

**Comment by dorchard** [comment]
Good idea. Sorted.

**Comment by vimuel** [comment]
Moved to a different discussion platform as not relevant to the current implementation.
