### ISSUE TITLE
Falsifiable example

### ISSUE THREAD

**Issue by vimuel** [dorchard/granule#52]
Counter example given is `n = 0`, I don't see why this would be wrong for the case `n = 0`, although something doesn't match up here: when `n = 1`, we can use the pattern match once, but we are using `m` twice. I tried `|n*2=|` but that still fails with the same counter-example.

```
factAlt : forall (n : Nat=) . (N n) |n| -> Int
factAlt x =
    case x of
      |Z| -> 1;
      |(S m)| -> (natToInt (S m)) * factAlt |m|
```

**Comment by dorchard** [comment]
Because we are producing a *linear* integer, we have to have at least one copy of the input in order to build it. So it should be `|n+1|`.
 Why are we using `m` twice? I see one use in the body and then it gets repackaged for the recursive call. 
Putting `n*2` would fail for the same reasons as mentioned for the first point.
