### ISSUE TITLE
Length-indexed lists

### ISSUE THREAD

**Issue by dorchard** [dorchard/granule#9]
As a specific (an interesting) instance of dependent types, it would be interesting to add an indexed family for sized lists, e.g., with a type `List n a` (lists of length `n` containing elements of type `a`). This will require some dependent pattern matching constructs in order to allow useful functions over sized lists. There are then lots of interesting possibilities of how this might interact with coeffects, in particular reuse bound coeffects (kind `Nat`) in the first instance.

Possible typings:

1.  `map : forall (c : Nat) . (|a| c -> b) -> |List n a| (n * c) -> List n b`

That is, for `map f x`  we need `n * c` copies of a  list `x` in order to apply the `f` function n-times which requires `c` copies of the input element.

2.  `map : forall (c : Nat) . (|a| c -> b) -> |List n (|a| c)| n -> List n b`

That is, for `map f x` we need `n` copies of `x` in order to apply `f` function n-times, but each element of the input list can be used `c` times. But how to promote the elements of a list?

3.  `map : forall (c : Nat) . (|a| c -> b) -> List n (|a| c) -> List n b`

The idea here is that the cons cells are being treated linearly, i.e., we don't need `n` copies of the input list, since each cons cell is used exactly once. Still need to promote elements (hm), but I think this version makes the most sense. Perhaps there is an additional axiom: `(List n a) |c| <-> List n (|a| c)`?

**Comment by vimuel** [comment]
I agree that 3 intuitively makes the most sense (and also seems most useful?), but I'll have to think about this a bit more.

**Comment by vimuel** [comment]
`List n a`—why not `Vector n a`?

**Comment by heades** [comment]
Considering the general case of an arbitrary semiring, it seems to me that 3 is the natural choice.  It fits better.  So the initial rule should fit it.  Given that, I wonder what needs to change in order to type  1 or 2, and should it be purely a property of the reuse coeffect?

1 is hard for me to understand.  I am not sure why `n` should interact with `c` since the former is about elements and the latter is about reuse.  

Perhaps it boils down to the fact that `f` is being used multiple times, and should be only used once?  Yeah, are we forgetting about this fact?  

The type `|a| c -> b` is a function that can use its input `c` times, but the type itself can only be used once, right?  So in order to use the function `n` times, we would need the type `|(|a| c -> b)| n`.

I might be misunderstanding something though.

So the typing for map I have in mind is:

``
map : forall (c : Nat) . |(|a| c -> b)| n -> List n (|a| c) -> List n b
``

What do you two think?

**Comment by dorchard** [comment]
Yes, you're absolutely right Harley. I forgot to include that! Yes, I think that should be the right type (Options 1 and 2 seem a bit odd really... I think it would depend on the typing/meaning of deconstruction). I wonder, how many programs are there that fit the above type? There are surely less than fit the usual polymorphic type of `map`. This is quite a nice feature of such typing: we've further limited the number of implementations. I think the class of programs captured by this type would be functorial behaviour on lists with permutations on finite sublists or something. So you can do:
```
map f Nil = Nil
map f (Cons x xs) = Cons (f x) (map f xs)
map f (Cons x (Cons y xs)) = Cons (f y) (Cons (f x) (map f xs))
```
But you couldn't drop elements, duplicate elements, or have all possible permutations (like reversing the list for all size lists)...

**Comment by dorchard** [comment]
(I don't mind `List` or `Vector` really).

**Comment by dorchard** [comment]
A version of this is now on `master` and it seems to be working great (we now have primitive recursion as a result). See the example in https://github.com/dorchard/granule/blob/master/examples/list.gr

I'm going to leave this project ticket open for a bit as I want to do a bit of refactoring to the type checking for this.

**Comment by dorchard** [comment]
Not also that "dependent pattern matching" is only possible in a top-level case and there is some rough edges with synthesising non top-level cases that I need to smooth out.

**Comment by dorchard** [comment]
In the long run, I think I will move away from having a dependent case, and instead push the dependency into the function clauses (in the style of Agda).
